const { useState, useMemo, useEffect } = React;
const {
  BarChart, Bar, LineChart, Line, ComposedChart, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, Cell, PieChart, Pie, Legend
} = Recharts;

/* ============================================================================
   METRA QC DASHBOARD — v3
   Single inspection-record data spine. Every chart, KPI and table on every
   tab is computed from the INSPECTIONS array (+ the CORRECTIVE_ACTIONS it
   generates) rather than hand-set numbers per tab, so the numbers can never
   drift out of sync with each other the way v2's did.

   SEED DATA NOTICE: the records below are generated by a seeded random
   function so every chart has real numbers to render on first load. They
   are clearly not real inspections. Replace them by logging real data
   through the "+ Log Inspection" and "+ Log Action" forms — new entries
   are appended to the same array everything else reads from, so the whole
   dashboard updates itself with zero other changes.
   ============================================================================ */

const DISTRICTS = [
  { id: "MD", label: "Milwaukee District", abbr: "MD", color: "#3B82F6", lines: ["MD-N", "MD-W"], yards: ["Western Ave", "Fox Lake"], baseline: 86, criticalProb: 0.03 },
  { id: "UP", label: "Union Pacific District", abbr: "UP", color: "#F59E0B", lines: ["UP-N", "UP-NW", "UP-W"], yards: ["OTC (Ogilvie Transportation Center)", "California Ave (M19A)", "Barrington", "Harvard", "McHenry"], baseline: 90, criticalProb: 0.02 },
  { id: "RI", label: "Rock Island District", abbr: "RI", color: "#EF4444", lines: ["RI → Joliet", "RI → Blue Island"], yards: ["Blue Island Yard", "KYD (Kensington)"], baseline: 66, criticalProb: 0.12 },
  { id: "MED", label: "Metra Electric District", abbr: "MED", color: "#10B981", lines: ["MED → Univ Park", "MED → South Chicago", "MED → Blue Island Yard"], yards: ["Millennium Station", "KYD (Kensington)", "Blue Island Yard"], baseline: 78, criticalProb: 0.06 },
  { id: "SWS", label: "South/Southwest Districts", abbr: "SWS", color: "#8B5CF6", lines: ["SouthWest Service (SWS)", "Heritage Corridor (HC)"], yards: ["KYD (Kensington)", "Blue Island Yard"], baseline: 61, criticalProb: 0.14 },
  { id: "BNSF", label: "BNSF Line", abbr: "BNSF", color: "#06B6D4", lines: ["BNSF Line"], yards: ["BNSF Yard (confirm name)"], baseline: 82, criticalProb: 0.04 },
];
const DIST_YARDS = Object.fromEntries(DISTRICTS.map(d => [d.id, d.yards]));
const DIST_LINES = Object.fromEntries(DISTRICTS.map(d => [d.id, d.lines]));
const DIST_MAP = Object.fromEntries(DISTRICTS.map(d => [d.id, d]));

/* ---------------------------------------------------------------------------
   REAL FLEET ROSTER — pulled from MetraCarRoster01_V4_6-8-16 (district PDFs),
   unique car numbers per district. Counts match each roster's own "Total
   cars" header exactly (MD 198, UP 329, RI 109, MED 149, BNSF 204), so these
   are the real car identifiers, not seed placeholders. SWS/HC has no
   roster file yet, so it still draws from a small synthetic pool below until
   real data is supplied for it.
   --------------------------------------------------------------------- */
const REAL_CAR_ROSTERS = {
  MD: ["6002","6003","6006","6013","6057","6088","6096","6117","6125","6130","6141","6143","6150","6159","6164","6168","6171","6175","6187","6193","6201","6202","6203","6204","6205","6206","6207","7217","7218","7233","7240","7250","7273","7274","7279","7282","7285","7289","7290","7291","7292","7293","7297","7298","7299","7300","7302","7303","7305","7309","7311","7314","7318","7325","7326","7328","7333","7336","7337","7338","7340","7343","7349","7405","7417","7427","7430","7431","7432","7433","7434","7435","7437","7439","7441","7442","7443","7447","7448","7449","7450","7453","7454","7455","7456","7457","7464","7467","7470","7478","7482","7484","7491","7494","7495","7659","7664","7801","7868","7885","8200","8201","8202","8203","8204","8205","8206","8207","8208","8209","8210","8211","8212","8213","8214","8215","8216","8217","8219","8220","8221","8223","8225","8226","8229","8230","8233","8234","8240","8242","8245","8248","8250","8253","8255","8256","8257","8258","8262","8263","8264","8273","8400","8401","8403","8412","8451","8462","8464","8468","8501","8502","8503","8505","8506","8508","8509","8510","8511","8512","8513","8514","8516","8517","8519","8521","8522","8523","8524","8525","8528","8529","8530","8531","8532","8533","8535","8537","8538","8539","8540","8541","8542","8543","8544","8546","8548","8553","8557","8564","8569","8572","8573","8575","8582","8587","8608","8749"],
  UP: ["6004","6005","6008","6010","6012","6014","6015","6016","6017","6018","6019","6020","6021","6022","6023","6024","6025","6026","6027","6028","6030","6031","6032","6033","6034","6035","6036","6037","6038","6039","6040","6041","6042","6043","6044","6045","6046","6047","6048","6049","6050","6051","6052","6053","6054","6055","6056","6058","6059","6060","6061","6063","6064","6065","6066","6067","6068","6069","6070","6071","6072","6073","6074","6075","6076","6077","6079","6080","6081","6082","6083","6084","6085","6086","6087","6089","6090","6091","6092","6093","6094","6095","6097","6098","6099","6100","6101","6102","6103","6104","6105","6106","6107","6108","6109","6110","6111","6112","6113","6114","6115","6116","6118","6119","6120","6121","6122","6123","6124","6126","6127","6128","6129","6131","6132","6133","6135","6136","6137","6138","6139","6140","6142","6144","6145","6146","6147","6148","6149","6151","6152","6153","6154","6155","6156","6157","6158","6160","6161","6162","6163","6165","6166","6167","6169","6170","6172","6173","6174","6176","6177","6178","6179","6180","6181","6182","6183","6190","6194","7108","7109","7113","7119","7202","7203","7204","7205","7206","7207","7208","7209","7210","7211","7212","7213","7214","7215","7216","7219","7221","7222","7223","7224","7225","7227","7228","7229","7230","7231","7232","7234","7235","7236","7237","7239","7241","7242","7243","7244","7245","7246","7247","7248","7249","7251","7252","7253","7255","7256","7257","7258","7259","7263","7264","7265","7268","7269","7275","7277","7281","7287","7288","7294","7301","7304","7306","7307","7319","7320","7323","7324","7341","7372","7418","7436","7451","7462","7466","7473","7476","7480","7496","7788","7789","7795","7804","7806","7810","7811","7816","7822","7862","8231","8236","8238","8239","8244","8247","8252","8259","8260","8261","8402","8404","8405","8406","8407","8408","8410","8411","8413","8414","8415","8416","8417","8418","8419","8420","8421","8422","8423","8424","8425","8426","8427","8428","8430","8431","8433","8434","8435","8436","8437","8439","8440","8441","8442","8443","8444","8446","8447","8449","8450","8452","8453","8454","8455","8456","8457","8458","8459","8460","8461","8463","8465","8466","8467","8470","8471","8472","8476","8477","8515","8520","8526","8527","8718","8738","8743"],
  RI: ["6001","6007","6009","6011","6029","6134","6192","7116","7117","7262","7276","7296","7308","7310","7312","7313","7315","7322","7331","7335","7346","7347","7348","7350","7352","7353","7354","7355","7356","7357","7358","7359","7360","7361","7362","7363","7364","7365","7366","7367","7370","7371","7373","7374","7375","7376","7377","7378","7379","7381","7400","7406","7461","7463","7474","7475","7477","7479","7483","7485","7486","7487","7490","7492","7493","7497","7787","7794","8235","8241","8246","8254","8265","8267","8268","8269","8270","8271","8272","8478","8504","8507","8534","8536","8547","8549","8550","8551","8552","8554","8555","8556","8558","8559","8560","8561","8562","8563","8565","8566","8567","8568","8570","8571","8574","8576","8580","8597","8598"],
  MED: ["1227","1228","1229","1230","1231","1232","1233","1234","1235","1236","1237","1238","1239","1240","1241","1242","1243","1244","1245","1246","1247","1248","1249","1250","1251","1253","1254","1255","1256","1257","1258","1259","1260","1261","1262","1263","1264","1265","1266","1267","1268","1270","1271","1273","1274","1275","1276","1277","1278","1279","1280","1281","1282","1283","1284","1285","1286","1287","1288","1289","1290","1291","1292","1293","1295","1296","1297","1298","1299","1300","1301","1302","1303","1304","1305","1307","1308","1310","1311","1312","1313","1314","1315","1316","1317","1318","1319","1320","1321","1322","1323","1324","1325","1326","1327","1328","1329","1330","1331","1332","1333","1334","1335","1336","1337","1338","1339","1340","1341","1342","1343","1346","1347","1348","1349","1350","1351","1352","1353","1354","1356","1357","1358","1359","1360","1361","1362","1363","1364","1365","1367","1368","1369","1370","1372","1373","1374","1375","1376","1377","1378","1379","1380","1381","1382","1383","1384","1385","1386"],
  BNSF: ["6062","6078","6184","6185","6186","6188","6189","6191","7100","7101","7102","7104","7105","7106","7107","7110","7111","7112","7114","7115","7118","7120","7121","7201","7220","7226","7238","7254","7260","7261","7266","7267","7270","7271","7272","7278","7280","7283","7284","7286","7295","7316","7317","7321","7327","7329","7330","7332","7334","7339","7342","7344","7345","7369","7380","7401","7402","7403","7404","7407","7408","7409","741","7410","7411","7412","7413","7414","7415","7416","7419","742","7420","7422","7423","7424","7425","7426","7428","7429","743","7438","744","7440","7444","7445","7446","7452","7458","7459","746","7460","7465","7468","7469","747","7471","7472","748","7481","7489","749","750","751","753","755","756","757","758","759","760","761","762","763","764","765","766","767","768","769","770","771","772","773","774","775","776","777","778","779","7791","780","782","783","784","785","786","787","798","799","801","803","804","805","808","809","810","811","812","813","814","815","816","817","818","819","820","8218","8224","8227","8228","8232","8237","8243","8251","8274","8275","8409","8429","8432","8438","8445","8448","8469","8474","8475","8518","8545","8577","8578","8579","8581","8583","8584","8585","8586","8588","8589","8590","8591","8592","8593","8594","8595","8596","8599","8600","8601","8602","8603","8604","8605","8606","8607"],
};

const EQUIP_TYPES = [
  { id: "Gallery Car", scheduledMin: 25 },
  { id: "Highliner", scheduledMin: 20 },
  { id: "Locomotive", scheduledMin: 15 },
];
const SHIFTS = ["AM", "PM"];
const TEAMS = ["Crew A", "Crew B", "Crew C"];
const SUPERVISORS = { MD: "T. Nowak", UP: "R. Alvarez", RI: "D. Fitzgerald", MED: "S. Okafor", SWS: "M. Bianchi", BNSF: "TBD" };
const CA_OWNERS = { MD: "T. Nowak", UP: "R. Alvarez", RI: "D. Fitzgerald", MED: "S. Okafor", SWS: "M. Bianchi", BNSF: "TBD", GF: "General Foreman" };
const INSPECTION_TYPES = ["Routine", "Unannounced", "Complaint-Driven", "Follow-up"];
const DEFECT_CATEGORIES = ["Floors", "Seating", "Windows/Glass", "Trash/Debris", "Odor", "Restroom", "Decals", "HVAC", "Exterior/Undercarriage", "Other"];
const DEFECT_WEIGHT_WEAK = ["Windows/Glass", "Trash/Debris", "Restroom", "Floors", "Odor"]; // what drags RI/SWS down
const DEFECT_WEIGHT_STRONG = ["Decals", "HVAC", "Seating", "Other"];
const ROOT_CAUSES = ["Staffing Shortage", "Short Layover / Time Constraint", "Supply Shortage", "Equipment/Tool Failure", "Training Gap", "High Ridership / Heavy Soiling", "Other / Undetermined"];
const SEV_CLR = { HIGH: "#EF4444", MED: "#F59E0B", LOW: "#10B981" };
const STS_CLR = { Open: "#EF4444", "In Progress": "#F59E0B", Closed: "#10B981" };
const MONTH_NAMES = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const DAY_MS = 86400000;

function mulberry32(seed) {
  return function () {
    seed |= 0; seed = (seed + 0x6D2B79F5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
function fmtDate(d) { return d.toISOString().slice(0, 10); }
function mostRecentMonday(d) { const x = new Date(d); const day = x.getDay(); const diff = (day === 0 ? 6 : day - 1); x.setDate(x.getDate() - diff); x.setHours(0, 0, 0, 0); return x; }
function addDays(d, n) { const x = new Date(d); x.setDate(x.getDate() + n); return x; }
function weekLabel(d) { return fmtDate(d); }
function monthLabel(d) { return `${MONTH_NAMES[d.getMonth()]} '${String(d.getFullYear()).slice(2)}`; }
function daysBetween(a, b) { return Math.round((b - a) / DAY_MS); }

/* ---------------------------------------------------------------------------
   SEED DATA GENERATION — 22 weeks ending the most recent Monday, so
   "overdue" flags on corrective actions are always computed against the
   real current date, not a date frozen at build time.
   --------------------------------------------------------------------- */
function buildSeedData() {
  const rand = mulberry32(1337);
  const ri = (min, max) => Math.floor(rand() * (max - min + 1)) + min;
  const pick = arr => arr[ri(0, arr.length - 1)];
  const clamp = (v, a, b) => Math.max(a, Math.min(b, v));

  const WEEKS = 22;
  const start = addDays(mostRecentMonday(new Date()), -WEEKS * 7);

  const inspections = [];
  const carPool = {};
  DISTRICTS.forEach(d => {
    carPool[d.id] = REAL_CAR_ROSTERS[d.id]
      ? REAL_CAR_ROSTERS[d.id]
      : Array.from({ length: 14 }, () => `${d.id}-${ri(4000, 9999)}`);
  });

  let idCounter = 1;
  for (let w = 0; w < WEEKS; w++) {
    const weekStart = addDays(start, w * 7);
    DISTRICTS.forEach(d => {
      SHIFTS.forEach(shift => {
        // 1-2 inspections per district/shift/week
        const n = rand() < 0.7 ? 1 : 2;
        for (let k = 0; k < n; k++) {
          const date = addDays(weekStart, ri(0, 4));
          if (date > new Date()) continue;
          const equip = pick(EQUIP_TYPES);
          const car = pick(carPool[d.id]);
          const yard = pick(d.yards);
          const inspectionType = rand() < 0.65 ? "Routine" : rand() < 0.7 ? "Unannounced" : rand() < 0.6 ? "Complaint-Driven" : "Follow-up";

          // mild, explicit trend improvement built into the seed so Trends has
          // something to show — flagged in the UI as seed data, not a real result
          const trendLift = Math.min(6, w * 0.28);
          let interior = clamp(Math.round(d.baseline + trendLift + ri(-9, 9)), 35, 100);
          const glass = clamp(interior - ri(2, 16), 25, 100);
          const criticalDefect = rand() < d.criticalProb;
          const fail = interior < 70 || criticalDefect;

          let defectCategory = "None", rootCause = "N/A";
          if (fail || rand() < 0.18) {
            const pool = (fail && rand() < 0.7) ? DEFECT_WEIGHT_WEAK : DEFECT_CATEGORIES;
            defectCategory = pick(d.criticalProb > 0.08 ? DEFECT_WEIGHT_WEAK.concat(pool) : pool);
            const rcPool = d.id === "RI" ? ["Short Layover / Time Constraint", "Short Layover / Time Constraint", "Staffing Shortage", "High Ridership / Heavy Soiling"]
              : d.id === "SWS" ? ["Staffing Shortage", "Supply Shortage", "Training Gap", "High Ridership / Heavy Soiling"]
              : ROOT_CAUSES;
            rootCause = pick(rcPool);
          }
          const complaintLinked = inspectionType === "Complaint-Driven" || (fail && rand() < 0.32);
          const scheduledMin = equip.scheduledMin - (yard.includes("Blue Island") || d.id === "RI" ? 6 : 0); // pick-and-flip yards get less time
          const actualMin = clamp(scheduledMin + ri(-7, 5), 6, scheduledMin + 8);
          const employees = ri(1, 3);

          inspections.push({
            id: idCounter++, date: fmtDate(date), weekEnding: fmtDate(addDays(weekStart, 6)), month: monthLabel(date),
            district: d.id, yard, train: `${d.id}-${ri(100, 899)}`, car, equipType: equip.id,
            shift, team: pick(TEAMS), supervisor: SUPERVISORS[d.id], inspectionType,
            scheduledMin, actualMin, employees,
            interior, glass, overall: interior, criticalDefect, fail,
            defectCategory, rootCause, complaintLinked, repeatDefect: false,
          });
        }
      });
    });
  }
  inspections.sort((a, b) => a.date.localeCompare(b.date));

  // repeat-defect pass: same car + same defect category within 30 days of an earlier one
  const lastSeen = {};
  inspections.forEach(r => {
    if (r.defectCategory === "None") return;
    const key = `${r.car}|${r.defectCategory}`;
    const prevDate = lastSeen[key];
    if (prevDate && daysBetween(new Date(prevDate), new Date(r.date)) <= 30) r.repeatDefect = true;
    lastSeen[key] = r.date;
  });

  // corrective actions generated from failed inspections
  const today = new Date();
  const actions = [];
  let caId = 1;
  inspections.filter(r => r.fail).forEach(r => {
    const opened = new Date(r.date);
    const due = addDays(opened, 8);
    const daysSinceOpen = daysBetween(opened, today);
    let status, dateClosed = null, reinspectionResult = "Pending", effectivenessVerified = false;
    if (daysSinceOpen < 3) status = "Open";
    else if (daysSinceOpen < 8) status = rand() < 0.55 ? "In Progress" : "Open";
    else {
      const roll = rand();
      status = roll < 0.82 ? "Closed" : roll < 0.91 ? "In Progress" : "Open";
      if (status === "Closed") {
        dateClosed = addDays(opened, Math.min(daysSinceOpen, ri(3, 20)));
        reinspectionResult = rand() < 0.85 ? "Pass" : "Fail";
        effectivenessVerified = reinspectionResult === "Pass" && rand() < 0.9;
      }
    }
    const severity = r.criticalDefect ? "HIGH" : r.interior < 55 ? "HIGH" : "MED";
    actions.push({
      id: caId++, inspectionId: r.id, district: r.district, yard: r.yard, line: pick(DIST_LINES[r.district]),
      car: r.car, issue: `${r.defectCategory === "None" ? "Critical defect" : r.defectCategory} — ${r.interior}% interior score`,
      category: r.defectCategory, rootCause: r.rootCause, severity, owner: CA_OWNERS[r.district],
      status, dateOpened: r.date, due: fmtDate(due), dateClosed: dateClosed ? fmtDate(dateClosed) : null,
      reinspectionResult, effectivenessVerified,
    });
  });

  return { inspections, actions };
}

const SEED = buildSeedData();

/* ---------------------------------------------------------------------------
   LIVE DATA ADAPTER — when this dashboard runs inside the Inspection Log, the
   log sends its real submitted inspections and corrective actions here. Once
   at least one real inspection exists, the dashboard switches off the seed
   data entirely and every tab is computed from the real records instead.
   --------------------------------------------------------------------- */
const EMBEDDED = window.parent && window.parent !== window;
function toDistrict(code) {
  if (!code) return "SWS";
  if (code === "MDN" || code === "MDW" || code === "MD") return "MD";
  if (code.indexOf("UP") === 0) return "UP";
  if (code === "SWS" || code === "HC") return "SWS";
  return DIST_MAP[code] ? code : "SWS";
}
function parseDay(str) { return new Date((str || fmtDate(new Date())) + "T12:00:00"); }
const WINDOW_AREAS = ["Lower Level Windows", "Upper Level Windows"];
function mapRealData(docs, cas) {
  const inspections = docs.filter(d => d && d.date).map(d => {
    const dt = parseDay(d.date);
    const areas = (d.areas || []).filter(a => a.score !== null && a.score !== undefined);
    const win = areas.filter(a => WINDOW_AREAS.indexOf(a.name) !== -1);
    const glass = win.length ? Math.round(win.reduce((s, a) => s + a.score * 20, 0) / win.length) : null;
    const worst = areas.filter(a => a.score <= 3).sort((a, b) => a.score - b.score)[0];
    const interior = typeof d.gradePct === "number" ? Math.round(d.gradePct) : 0;
    const criticalDefect = (d.criticalCount || 0) > 0;
    const linkedCa = (cas || []).find(c => c.sourceInspectionId === d._id && (c.confirmedRootCause || c.probableCause));
    return {
      id: d._id, date: d.date, weekEnding: fmtDate(addDays(mostRecentMonday(dt), 6)), month: monthLabel(dt),
      district: toDistrict(d.district), line: d.district || "", yard: d.yard || "Unspecified yard", train: d.trainNumber || "", car: d.railcarNumber || "",
      equipType: "Not recorded", shift: d.shift || "AM", team: "—", supervisor: d.supervisor || "—", inspectionType: d.inspectionType || "Routine",
      scheduledMin: typeof d.scheduledMin === "number" ? d.scheduledMin : null,
      actualMin: typeof d.actualMin === "number" ? d.actualMin : null,
      employees: null,
      interior, glass: glass === null ? interior : glass, overall: interior, criticalDefect,
      fail: interior < 70 || criticalDefect,
      defectCategory: worst ? worst.name : "None",
      rootCause: worst ? (linkedCa ? (linkedCa.confirmedRootCause || linkedCa.probableCause) : "Not yet determined") : "N/A",
      complaintLinked: d.inspectionType === "Complaint-Driven" || !!d.jiraTicket,
      repeatDefect: false,
    };
  }).sort((a, b) => a.date.localeCompare(b.date));
  const lastSeen = {};
  inspections.forEach(r => {
    if (r.defectCategory === "None") return;
    const key = `${r.car}|${r.defectCategory}`;
    const prevDate = lastSeen[key];
    if (prevDate && daysBetween(new Date(prevDate), new Date(r.date)) <= 30) r.repeatDefect = true;
    lastSeen[key] = r.date;
  });
  const inspById = Object.fromEntries(inspections.map(r => [r.id, r]));
  const actions = (cas || []).map(c => {
    const src = inspById[c.sourceInspectionId];
    const closed = c.status === "Completed" || c.status === "Verified";
    return {
      id: c._id, inspectionId: c.sourceInspectionId, district: toDistrict(c.district), yard: src ? src.yard : "—", line: c.district || "",
      car: c.railcarNumber || "", issue: `${c.area || "Area"} (${c.severity || "exception"})${c.defectDescription ? " · " + c.defectDescription : ""}`,
      category: c.area || "Other", rootCause: c.confirmedRootCause || c.probableCause || "Not yet determined",
      severity: c.severity === "NO-GO" ? "HIGH" : "MED", owner: c.owner || "Unassigned",
      status: closed ? "Closed" : (c.status === "In Progress" ? "In Progress" : "Open"),
      dateOpened: c.assignedDate || fmtDate(new Date()), due: c.dueDate || "", dateClosed: closed ? (c.completionDate || c.verifiedDate || null) : null,
      reinspectionResult: c.reinspectionResult === "Pass" ? "Pass" : c.reinspectionResult ? "Fail" : "Pending",
      effectivenessVerified: !!c.effectivenessVerified,
    };
  });
  return { inspections, actions };
}

/* ---------------------------------------------------------------------------
   Shared UI atoms
   --------------------------------------------------------------------- */
function Tag({ label, color }) {
  return <span style={{ fontSize: 9, fontWeight: 700, color, background: `${color}18`, border: `1px solid ${color}40`, padding: "2px 7px", borderRadius: 4, fontFamily: "monospace" }}>{label}</span>;
}
function KPICard({ label, value, sub, color, trend }) {
  return (
    <div style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 14, padding: "20px 22px", flex: 1, minWidth: 150, position: "relative", overflow: "hidden" }}>
      <div style={{ position: "absolute", top: 0, left: 0, right: 0, height: 3, background: color }} />
      <div style={{ fontSize: 9, color: "#64748B", letterSpacing: "0.12em", textTransform: "uppercase", fontFamily: "monospace", marginBottom: 8 }}>{label}</div>
      <div style={{ fontSize: 32, fontWeight: 800, color: "#F1F5F9", lineHeight: 1 }}>{value}</div>
      {sub && <div style={{ fontSize: 10, color: "#475569", marginTop: 6, fontFamily: "monospace" }}>{sub}</div>}
      {trend && <div style={{ fontSize: 10, color: trend.up ? "#10B981" : "#EF4444", marginTop: 8, fontFamily: "monospace" }}>{trend.up ? "▲" : "▼"} {trend.label}</div>}
    </div>
  );
}
function SecTitle({ children, color = "#3B82F6" }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 16 }}>
      <div style={{ width: 3, height: 16, background: color, borderRadius: 2 }} />
      <span style={{ fontSize: 10, fontWeight: 700, color: "#94A3B8", letterSpacing: "0.12em", textTransform: "uppercase", fontFamily: "monospace" }}>{children}</span>
    </div>
  );
}
function Card({ children, style }) {
  return <div style={{ background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: 14, padding: 22, ...style }}>{children}</div>;
}
function ScoreColor(v) { return v >= 80 ? "#10B981" : v >= 65 ? "#F59E0B" : "#EF4444"; }
function Field({ label, children }) {
  return <div style={{ display: "flex", flexDirection: "column", gap: 4, minWidth: 110 }}><label style={{ fontSize: 8, color: "#64748B", fontFamily: "monospace" }}>{label}</label>{children}</div>;
}
const inputStyle = { background: "#111C2E", border: "1px solid rgba(255,255,255,0.1)", color: "#CBD5E1", padding: "6px 10px", borderRadius: 7, fontSize: 12 };

/* ============================================================================ */

function MetraDashboard() {
  const [tab, setTab] = useState("overview");
  const [inspections, setInspections] = useState(SEED.inspections);
  const [actions, setActions] = useState(SEED.actions);
  // "seed" until the Inspection Log hands over at least one real inspection, then "live".
  const [dataMode, setDataMode] = useState("seed");
  const [feedConnected, setFeedConnected] = useState(false);
  const [baselineCount, setBaselineCount] = useState(0);
  const isLive = dataMode === "live";

  useEffect(() => {
    if (!EMBEDDED) return;
    function onMsg(e) {
      if (e.origin !== window.location.origin || !e.data || e.data.type !== "qc-data") return;
      setFeedConnected(!!e.data.connected);
      setBaselineCount(e.data.baselineCount || 0);
      const docs = e.data.inspections || [];
      if (docs.length > 0) {
        const real = mapRealData(docs, e.data.actions || []);
        setInspections(real.inspections);
        setActions(real.actions);
        setDataMode("live");
      } else {
        setInspections(SEED.inspections);
        setActions(SEED.actions);
        setDataMode("seed");
      }
    }
    window.addEventListener("message", onMsg);
    window.parent.postMessage({ type: "qc-ready" }, window.location.origin);
    return () => window.removeEventListener("message", onMsg);
  }, []);

  const [selDistrict, setSelDistrict] = useState(null);
  const [fDist, setFDist] = useState("All");
  const [fStatus, setFStatus] = useState("All");
  const [fSev, setFSev] = useState("All");
  const [fOverdueOnly, setFOverdueOnly] = useState(false);
  const [showActionForm, setShowActionForm] = useState(false);
  const [showInspForm, setShowInspForm] = useState(false);
  const [trendDist, setTrendDist] = useState("All");

  const [na, setNa] = useState({ district: "MD", yard: DIST_YARDS.MD[0], line: DIST_LINES.MD[0], car: "", issue: "", category: "Floors", rootCause: "Staffing Shortage", severity: "MED", owner: CA_OWNERS.MD, due: "" });
  const [ni, setNi] = useState({ district: "MD", yard: DIST_YARDS.MD[0], car: "", shift: "AM", inspectionType: "Routine", interior: 85, glass: 80, criticalDefect: false, defectCategory: "None" });

  const today = new Date();

  /* ---- derived, system-wide ---- */
  const totalInsp = inspections.length;
  const avgScore = totalInsp ? Math.round(inspections.reduce((s, r) => s + r.interior, 0) / totalInsp) : 0;
  const passCount = inspections.filter(r => !r.fail).length;
  const passRate = totalInsp ? Math.round((passCount / totalInsp) * 100) : 0;
  const criticalCount = inspections.filter(r => r.criticalDefect).length;
  const criticalRate = totalInsp ? Math.round((criticalCount / totalInsp) * 1000) / 10 : 0;
  const defectRecords = inspections.filter(r => r.defectCategory !== "None");
  const repeatCount = inspections.filter(r => r.repeatDefect).length;
  const repeatRate = defectRecords.length ? Math.round((repeatCount / defectRecords.length) * 100) : 0;
  const complaintCount = inspections.filter(r => r.complaintLinked).length;

  const openActions = actions.filter(a => a.status !== "Closed");
  const overdueActions = openActions.filter(a => a.due && new Date(a.due) < today);
  const closedActions = actions.filter(a => a.status === "Closed");
  const caClosureRate = actions.length ? Math.round((closedActions.length / actions.length) * 100) : 100;
  const onTimeClosed = closedActions.filter(a => a.dateClosed && (!a.due || new Date(a.dateClosed) <= new Date(a.due)));
  const onTimeRate = closedActions.length ? Math.round((onTimeClosed.length / closedActions.length) * 100) : 0;
  const closedWithDates = closedActions.filter(a => a.dateClosed);
  const avgDaysToClose = closedWithDates.length ? Math.round(closedWithDates.reduce((s, a) => s + daysBetween(new Date(a.dateOpened), new Date(a.dateClosed)), 0) / closedWithDates.length) : 0;
  const effectivenessRate = closedActions.length ? Math.round((closedActions.filter(a => a.effectivenessVerified).length / closedActions.length) * 100) : 0;

  /* ---- monthly complaint / score trend (computed, not hardcoded) ---- */
  const monthOrder = [];
  const monthMap = {};
  inspections.forEach(r => {
    if (!monthMap[r.month]) { monthMap[r.month] = { month: r.month, complaints: 0, scores: [] }; monthOrder.push(r.month); }
    monthMap[r.month].complaints += r.complaintLinked ? 1 : 0;
    monthMap[r.month].scores.push(r.interior);
  });
  const monthlyTrend = monthOrder.map(m => ({ month: m, complaints: monthMap[m].complaints, avgScore: Math.round(monthMap[m].scores.reduce((a, b) => a + b, 0) / monthMap[m].scores.length) }));
  const firstMonth = monthlyTrend[0];
  const lastMonth = monthlyTrend[monthlyTrend.length - 1];
  const complaintPctChange = firstMonth && firstMonth.complaints > 0
    ? Math.round(((lastMonth.complaints - firstMonth.complaints) / firstMonth.complaints) * 100)
    : null;

  /* ---- per-district rollups ---- */
  const districtStats = DISTRICTS.map(d => {
    const rows = inspections.filter(r => r.district === d.id);
    const n = rows.length || 1;
    const hasData = rows.length > 0;
    const score = Math.round(rows.reduce((s, r) => s + r.interior, 0) / n);
    const glassScore = Math.round(rows.reduce((s, r) => s + r.glass, 0) / n);
    const complaints = rows.filter(r => r.complaintLinked).length;
    const dActions = actions.filter(a => a.district === d.id);
    const dClosed = dActions.filter(a => a.status === "Closed").length;
    const dCaRate = dActions.length ? Math.round((dClosed / dActions.length) * 100) : 100;
    const inspComplete = rows.length; // routine cadence proxy: inspections logged this window
    const complaintScore = Math.max(0, 100 - complaints * 6);
    const qcIndex = hasData ? Math.round(score * 0.60 + complaintScore * 0.20 + dCaRate * 0.12 + Math.min(100, inspComplete * 4) * 0.08) : null;
    const dOverdue = dActions.filter(a => a.status !== "Closed" && a.due && new Date(a.due) < today).length;
    return { ...d, hasData, score: hasData ? score : null, glassScore: hasData ? glassScore : null, complaints, qcIndex, inspCount: rows.length, dOverdue, dOpen: dActions.filter(a => a.status !== "Closed").length };
  });

  /* ---- Pareto: defect category frequency ---- */
  const catCounts = {};
  defectRecords.forEach(r => { catCounts[r.defectCategory] = (catCounts[r.defectCategory] || 0) + 1; });
  const paretoSorted = Object.entries(catCounts).sort((a, b) => b[1] - a[1]);
  const paretoTotal = paretoSorted.reduce((s, [, v]) => s + v, 0) || 1;
  let running = 0;
  const paretoData = paretoSorted.map(([name, value]) => {
    running += value;
    return { name, value, cumPct: Math.round((running / paretoTotal) * 100) };
  });

  /* ---- root cause breakdown ---- */
  const rcCounts = {};
  defectRecords.forEach(r => { if (r.rootCause !== "N/A") rcCounts[r.rootCause] = (rcCounts[r.rootCause] || 0) + 1; });
  const rootCauseData = Object.entries(rcCounts).sort((a, b) => b[1] - a[1]).map(([name, value]) => ({ name, value }));

  /* ---- heat map: district x shift, avg score ---- */
  const heatData = DISTRICTS.map(d => {
    const cells = SHIFTS.map(sh => {
      const rows = inspections.filter(r => r.district === d.id && r.shift === sh);
      const n = rows.length || 1;
      return { shift: sh, avgScore: rows.length ? Math.round(rows.reduce((s, r) => s + r.interior, 0) / n) : null, n: rows.length, failRate: rows.length ? Math.round((rows.filter(r => r.fail).length / n) * 100) : null };
    });
    return { district: d, cells };
  });

  /* ---- staffing / productivity: planned vs actual time by yard ---- */
  const yardStats = {};
  inspections.forEach(r => {
    if (!yardStats[r.yard]) yardStats[r.yard] = { yard: r.yard, district: r.district, scheduled: [], actual: [], scores: [] };
    yardStats[r.yard].scheduled.push(r.scheduledMin);
    yardStats[r.yard].actual.push(r.actualMin);
    yardStats[r.yard].scores.push(r.interior);
  });
  const avgOf = arr => { const v = arr.filter(x => typeof x === "number" && isFinite(x)); return v.length ? Math.round(v.reduce((a, b) => a + b, 0) / v.length) : null; };
  const fmtMin = v => v === null ? "—" : `${v} min`;
  const yardRows = Object.values(yardStats).map(y => {
    const sch = avgOf(y.scheduled), act = avgOf(y.actual);
    return { yard: y.yard, district: y.district, scheduledMin: sch, actualMin: act,
      delta: sch !== null && act !== null ? act - sch : null, avgScore: avgOf(y.scores), n: y.scores.length };
  }).sort((a, b) => (a.delta === null ? 999 : a.delta) - (b.delta === null ? 999 : b.delta));

  /* ---- filtered actions table ---- */
  const filteredActions = actions.filter(a =>
    (fDist === "All" || a.district === fDist) &&
    (fStatus === "All" || a.status === fStatus) &&
    (fSev === "All" || a.severity === fSev) &&
    (!fOverdueOnly || (a.status !== "Closed" && a.due && new Date(a.due) < today))
  ).sort((a, b) => b.dateOpened.localeCompare(a.dateOpened));

  const stsCounts = ["Open", "In Progress", "Closed"].map(s => ({ name: s, value: actions.filter(a => a.status === s).length }));

  function toggleStatus(id) {
    if (isLive) {
      const cur = actions.find(a => a.id === id);
      if (!cur) return;
      const nxt = { Open: "In Progress", "In Progress": "Closed", Closed: "Open" }[cur.status];
      window.parent.postMessage({ type: "qc-ca-status", id, status: nxt }, window.location.origin);
    }
    setActions(actions.map(a => {
      if (a.id !== id) return a;
      const nxt = { Open: "In Progress", "In Progress": "Closed", Closed: "Open" };
      const status = nxt[a.status];
      return { ...a, status, dateClosed: status === "Closed" ? fmtDate(today) : null, reinspectionResult: status === "Closed" ? "Pending" : a.reinspectionResult };
    }));
  }

  function addAction() {
    if (!na.issue || !na.due) return;
    setActions([...actions, { ...na, id: Date.now(), inspectionId: null, status: "Open", dateOpened: fmtDate(today), dateClosed: null, reinspectionResult: "Pending", effectivenessVerified: false }]);
    setNa({ district: "MD", yard: DIST_YARDS.MD[0], line: DIST_LINES.MD[0], car: "", issue: "", category: "Floors", rootCause: "Staffing Shortage", severity: "MED", owner: CA_OWNERS.MD, due: "" });
    setShowActionForm(false);
  }

  function addInspection() {
    if (!ni.car.trim()) return;
    const fail = ni.interior < 70 || ni.criticalDefect;
    const row = {
      id: Date.now(), date: fmtDate(today), weekEnding: fmtDate(addDays(mostRecentMonday(today), 6)), month: monthLabel(today),
      district: ni.district, yard: ni.yard, train: `${ni.district}-LOG`, car: ni.car.trim().toUpperCase(), equipType: "Gallery Car",
      shift: ni.shift, team: "Crew A", supervisor: SUPERVISORS[ni.district], inspectionType: ni.inspectionType,
      scheduledMin: 25, actualMin: 25, employees: 2,
      interior: Number(ni.interior), glass: Number(ni.glass), overall: Number(ni.interior),
      criticalDefect: ni.criticalDefect, fail, defectCategory: ni.defectCategory, rootCause: ni.defectCategory !== "None" ? "Other / Undetermined" : "N/A",
      complaintLinked: ni.inspectionType === "Complaint-Driven", repeatDefect: false,
    };
    setInspections([...inspections, row]);
    if (fail) {
      setActions(prev => [...prev, {
        id: Date.now() + 1, inspectionId: row.id, district: row.district, yard: row.yard, line: DIST_LINES[row.district][0],
        car: row.car, issue: `${row.defectCategory === "None" ? "Critical defect" : row.defectCategory} — ${row.interior}% interior score`,
        category: row.defectCategory, rootCause: row.rootCause, severity: row.criticalDefect ? "HIGH" : "MED", owner: CA_OWNERS[row.district],
        status: "Open", dateOpened: row.date, due: fmtDate(addDays(today, 8)), dateClosed: null, reinspectionResult: "Pending", effectivenessVerified: false,
      }]);
    }
    setNi({ district: "MD", yard: DIST_YARDS.MD[0], car: "", shift: "AM", inspectionType: "Routine", interior: 85, glass: 80, criticalDefect: false, defectCategory: "None" });
    setShowInspForm(false);
  }

  const TABS = ["overview", "districts", "trends", "defects", "actions", "staffing", "complaints"];
  const TAB_LABELS = { overview: "Overview", districts: "Districts & Yards", trends: "Trends", defects: "Defects & Root Cause", actions: "Corrective Actions", staffing: "Staffing & Productivity", complaints: "Complaints" };

  return (
    <div style={{ minHeight: "100vh", background: "#07101E", color: "#F1F5F9", fontFamily: "'Segoe UI', sans-serif" }}>
      <style>{`
        .qcd-grid5 { display: grid; grid-template-columns: repeat(6,1fr); gap: 10px; }
        .qcd-grid2 { display: grid; grid-template-columns: 1fr 1fr; gap: 18px; }
        .qcd-grid3b { display: grid; grid-template-columns: repeat(3,1fr); gap: 12px; }
        .qcd-split { display: grid; grid-template-columns: 2fr 1fr; gap: 18px; }
        .qcd-tabs::-webkit-scrollbar { height: 4px; }
        @media (max-width: 900px) { .qcd-split, .qcd-grid2 { grid-template-columns: 1fr; } }
        @media (max-width: 760px) { .qcd-grid5 { grid-template-columns: repeat(2,1fr); } .qcd-grid3b { grid-template-columns: 1fr; } }
        @media (max-width: 420px) { .qcd-grid5 { grid-template-columns: 1fr; } }
      `}</style>

      {/* HEADER */}
      <div style={{ background: "linear-gradient(135deg,#0A1628,#0F1F3D)", borderBottom: "1px solid rgba(255,255,255,0.07)", padding: "clamp(14px,3.5vw,22px) clamp(14px,4vw,32px) 0", position: "sticky", top: 0, zIndex: 100 }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", rowGap: 12, marginBottom: 18 }}>
          <div>
            <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 4 }}>
              <div style={{ width: 7, height: 7, borderRadius: "50%", background: "#10B981", boxShadow: "0 0 7px #10B981", flexShrink: 0 }} />
              <span style={{ fontSize: 10, color: "#10B981", fontFamily: "monospace", letterSpacing: "0.12em" }}>METRA QC — GENERAL FOREMAN DASHBOARD · v3</span>
            </div>
            <h1 style={{ margin: 0, fontSize: "clamp(18px,4.5vw,22px)", fontWeight: 800, letterSpacing: "-0.02em" }}>
              QC Control Center <span style={{ color: "#3B82F6" }}>— All Districts</span>
            </h1>
            <p style={{ margin: "3px 0 0", fontSize: 11, color: "#475569", fontFamily: "monospace" }}>MD · UP · RI · MED · SWS/HC · BNSF · {totalInsp} inspections logged</p>
          </div>
          <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
            {[{ l: "Complaints", v: complaintCount, c: "#EF4444" }, { l: "Avg Score", v: `${avgScore}%`, c: "#3B82F6" }, { l: "Overdue Actions", v: overdueActions.length, c: overdueActions.length ? "#EF4444" : "#10B981" }].map(k => (
              <div key={k.l} style={{ textAlign: "center", padding: "8px 14px", background: `${k.c}12`, border: `1px solid ${k.c}30`, borderRadius: 10 }}>
                <div style={{ fontSize: 9, color: "#64748B", fontFamily: "monospace" }}>{k.l}</div>
                <div style={{ fontSize: 20, fontWeight: 800, color: k.c }}>{k.v}</div>
              </div>
            ))}
          </div>
        </div>
        <div className="qcd-tabs" style={{ display: "flex", overflowX: "auto", WebkitOverflowScrolling: "touch" }}>
          {TABS.map(t => (
            <button key={t} onClick={() => setTab(t)} style={{ background: "none", border: "none", cursor: "pointer", padding: "9px 16px", fontSize: 12, color: tab === t ? "#F1F5F9" : "#475569", borderBottom: `2px solid ${tab === t ? "#3B82F6" : "transparent"}`, transition: "all 0.15s", whiteSpace: "nowrap", flexShrink: 0 }}>
              {TAB_LABELS[t]}
            </button>
          ))}
        </div>
      </div>

      <div style={{ padding: "10px clamp(14px,4vw,32px) 0" }}>
        {isLive ? (
          <div style={{ padding: "8px 14px", background: "rgba(16,185,129,0.08)", border: "1px solid rgba(16,185,129,0.3)", borderRadius: 8, fontSize: 10, color: "#34D399", fontFamily: "monospace", marginBottom: 6 }}>
            ● LIVE DATA — {totalInsp} real inspection{totalInsp === 1 ? "" : "s"} and {actions.length} corrective action{actions.length === 1 ? "" : "s"} from the Inspection Log (after-cleaning only{baselineCount ? `; ${baselineCount} arrival baseline${baselineCount === 1 ? "" : "s"} excluded, see Live Stats` : ""}). No seed data in use.{totalInsp < 30 ? " Early sample: treat trends and district rankings as directional until roughly 30 days of inspections are in." : ""}
          </div>
        ) : (
          <div style={{ padding: "8px 14px", background: "rgba(245,158,11,0.08)", border: "1px solid rgba(245,158,11,0.25)", borderRadius: 8, fontSize: 10, color: "#FBBF24", fontFamily: "monospace", marginBottom: 6 }}>
            ⚠ SEED DATA — {EMBEDDED && feedConnected ? "connected to the Inspection Log, but no real inspections have been submitted yet." : "not yet connected to real inspections."} The {totalInsp} scores shown are demo data on real roster car numbers. This notice disappears and the dashboard switches to real data automatically as soon as the first inspection is transmitted.
          </div>
        )}
      </div>

      <div style={{ padding: "clamp(10px,4vw,16px) clamp(14px,4vw,32px) clamp(16px,4vw,26px)" }}>

        {/* OVERVIEW */}
        {tab === "overview" && (
          <div>
            <div style={{ display: "flex", gap: 8, marginBottom: 16 }}>
              <button onClick={() => EMBEDDED ? window.parent.postMessage({ type: "qc-open-new" }, window.location.origin) : setShowInspForm(!showInspForm)} style={{ marginLeft: "auto", background: "#3B82F6", border: "none", color: "#fff", padding: "8px 16px", borderRadius: 8, cursor: "pointer", fontSize: 12, fontWeight: 600 }}>+ Log Inspection</button>
            </div>
            {showInspForm && (
              <div style={{ background: "rgba(59,130,246,0.07)", border: "1px solid rgba(59,130,246,0.2)", borderRadius: 12, padding: 16, marginBottom: 18, display: "flex", gap: 10, flexWrap: "wrap", alignItems: "flex-end" }}>
                <Field label="DISTRICT"><select value={ni.district} onChange={e => setNi({ ...ni, district: e.target.value, yard: DIST_YARDS[e.target.value][0] })} style={inputStyle}>{DISTRICTS.map(d => <option key={d.id} value={d.id}>{d.id}</option>)}</select></Field>
                <Field label="YARD"><select value={ni.yard} onChange={e => setNi({ ...ni, yard: e.target.value })} style={inputStyle}>{DIST_YARDS[ni.district].map(y => <option key={y} value={y}>{y}</option>)}</select></Field>
                <Field label="CAR #"><input type="text" value={ni.car} placeholder="e.g. 7714" onChange={e => setNi({ ...ni, car: e.target.value })} style={inputStyle} /></Field>
                <Field label="SHIFT"><select value={ni.shift} onChange={e => setNi({ ...ni, shift: e.target.value })} style={inputStyle}>{SHIFTS.map(s => <option key={s}>{s}</option>)}</select></Field>
                <Field label="TYPE"><select value={ni.inspectionType} onChange={e => setNi({ ...ni, inspectionType: e.target.value })} style={inputStyle}>{INSPECTION_TYPES.map(s => <option key={s}>{s}</option>)}</select></Field>
                <Field label="INTERIOR (0-100)"><input type="number" value={ni.interior} onChange={e => setNi({ ...ni, interior: e.target.value })} style={inputStyle} /></Field>
                <Field label="GLASS (0-100)"><input type="number" value={ni.glass} onChange={e => setNi({ ...ni, glass: e.target.value })} style={inputStyle} /></Field>
                <Field label="DEFECT CATEGORY"><select value={ni.defectCategory} onChange={e => setNi({ ...ni, defectCategory: e.target.value })} style={inputStyle}><option>None</option>{DEFECT_CATEGORIES.map(c => <option key={c}>{c}</option>)}</select></Field>
                <label style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 11, color: "#CBD5E1" }}><input type="checkbox" checked={ni.criticalDefect} onChange={e => setNi({ ...ni, criticalDefect: e.target.checked })} /> Critical defect</label>
                <button onClick={addInspection} style={{ background: "#10B981", border: "none", color: "#fff", padding: "8px 16px", borderRadius: 8, cursor: "pointer", fontSize: 12, fontWeight: 600 }}>Save</button>
              </div>
            )}

            <div style={{ display: "flex", gap: 12, marginBottom: 22, flexWrap: "wrap" }}>
              <KPICard label="Avg Cleanliness Score" value={`${avgScore}%`} sub={`${totalInsp} inspections`} color="#3B82F6" />
              <KPICard label="Inspection Pass Rate" value={`${passRate}%`} sub={`${passCount}/${totalInsp} passed`} color="#10B981" />
              <KPICard label="Complaints" value={complaintCount} sub={complaintPctChange !== null ? `${complaintPctChange >= 0 ? "+" : ""}${complaintPctChange}% vs ${firstMonth.month}` : "Complaint-linked inspections"} color="#EF4444" trend={complaintPctChange !== null ? { up: complaintPctChange <= 0, label: `${complaintPctChange}% vs first month logged` } : null} />
              <KPICard label="Critical Defects" value={criticalCount} sub={`${criticalRate}% of inspections`} color="#F59E0B" />
              <KPICard label="Repeat-Defect Rate" value={`${repeatRate}%`} sub={`${repeatCount} of ${defectRecords.length} defects`} color="#8B5CF6" />
              <KPICard label="Open / Overdue Actions" value={`${openActions.length} / ${overdueActions.length}`} sub={`${caClosureRate}% closed all-time`} color={overdueActions.length ? "#EF4444" : "#10B981"} />
            </div>

            <div className="qcd-grid5" style={{ marginBottom: 22 }}>
              {districtStats.map(d => (
                <div key={d.id} onClick={() => { setSelDistrict(d.id); setTab("districts"); }}
                  style={{ background: "rgba(255,255,255,0.02)", border: `1px solid ${d.color}30`, borderRadius: 12, padding: 16, cursor: "pointer" }}>
                  <div style={{ fontSize: 10, color: "#64748B", fontFamily: "monospace", marginBottom: 4 }}>{d.abbr}</div>
                  <div style={{ fontSize: 26, fontWeight: 800, color: d.qcIndex === null ? "#475569" : ScoreColor(d.qcIndex) }}>{d.qcIndex === null ? "—" : `${d.qcIndex}%`}</div>
                  <div style={{ fontSize: 9, color: "#475569", fontFamily: "monospace" }}>{d.qcIndex === null ? "No inspections yet" : `QC Index · ${d.complaints} complaints`}</div>
                  <div style={{ marginTop: 8, height: 4, background: "rgba(255,255,255,0.07)", borderRadius: 2 }}>
                    <div style={{ height: "100%", width: `${d.qcIndex || 0}%`, background: d.color, borderRadius: 2 }} />
                  </div>
                  {d.dOverdue > 0 && <div style={{ marginTop: 8 }}><Tag label={`${d.dOverdue} overdue`} color="#EF4444" /></div>}
                </div>
              ))}
            </div>

            <div className="qcd-split">
              <Card>
                <SecTitle>Complaint & Score Trend — All Districts, By Month</SecTitle>
                <ResponsiveContainer width="100%" height={230}>
                  <ComposedChart data={monthlyTrend}>
                    <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                    <XAxis dataKey="month" tick={{ fill: "#64748B", fontSize: 10, fontFamily: "monospace" }} axisLine={false} tickLine={false} />
                    <YAxis yAxisId="l" tick={{ fill: "#64748B", fontSize: 10 }} axisLine={false} tickLine={false} />
                    <YAxis yAxisId="r" orientation="right" domain={[0, 100]} tick={{ fill: "#64748B", fontSize: 10 }} axisLine={false} tickLine={false} />
                    <Tooltip contentStyle={{ background: "#1E293B", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 8, color: "#F1F5F9", fontSize: 11 }} />
                    <Legend wrapperStyle={{ fontSize: 10, fontFamily: "monospace", color: "#64748B" }} />
                    <Bar yAxisId="l" dataKey="complaints" fill="#EF444480" name="Complaints" radius={[4, 4, 0, 0]} />
                    <Line yAxisId="r" type="monotone" dataKey="avgScore" stroke="#3B82F6" strokeWidth={2.5} dot={{ r: 3, fill: "#3B82F6" }} name="Avg Score" />
                  </ComposedChart>
                </ResponsiveContainer>
              </Card>
              <Card>
                <SecTitle>Action Status</SecTitle>
                <ResponsiveContainer width="100%" height={140}>
                  <PieChart>
                    <Pie data={stsCounts} cx="50%" cy="50%" innerRadius={42} outerRadius={64} dataKey="value" paddingAngle={3}>
                      {stsCounts.map(e => <Cell key={e.name} fill={STS_CLR[e.name]} />)}
                    </Pie>
                    <Tooltip contentStyle={{ background: "#1E293B", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 8, color: "#F1F5F9", fontSize: 11 }} />
                  </PieChart>
                </ResponsiveContainer>
                <div style={{ display: "flex", flexDirection: "column", gap: 8, marginTop: 8 }}>
                  {stsCounts.map(s => (
                    <div key={s.name} style={{ display: "flex", justifyContent: "space-between" }}>
                      <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                        <div style={{ width: 8, height: 8, borderRadius: 2, background: STS_CLR[s.name] }} />
                        <span style={{ fontSize: 11, color: "#94A3B8", fontFamily: "monospace" }}>{s.name}</span>
                      </div>
                      <span style={{ fontSize: 14, fontWeight: 700, color: "#F1F5F9" }}>{s.value}</span>
                    </div>
                  ))}
                </div>
              </Card>
            </div>

            <div style={{ marginTop: 18, padding: "16px 20px", background: "rgba(239,68,68,0.06)", border: "1px solid rgba(239,68,68,0.2)", borderRadius: 12 }}>
              <div style={{ fontSize: 10, fontWeight: 700, color: "#FCA5A5", fontFamily: "monospace", marginBottom: 10 }}>RISKS REQUIRING ATTENTION</div>
              <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                {overdueActions.length > 0 && <div style={{ fontSize: 12, color: "#E2E8F0" }}>• {overdueActions.length} corrective action{overdueActions.length !== 1 ? "s are" : " is"} past due — see Corrective Actions tab, "Overdue only" filter.</div>}
                {districtStats.filter(d => d.qcIndex !== null && d.qcIndex < 70).map(d => <div key={d.id} style={{ fontSize: 12, color: "#E2E8F0" }}>• {d.label} QC Index at {d.qcIndex}%, below the 70% floor.</div>)}
                {repeatRate > 25 && <div style={{ fontSize: 12, color: "#E2E8F0" }}>• Repeat-defect rate at {repeatRate}% — corrective actions may not be addressing root cause.</div>}
                {overdueActions.length === 0 && districtStats.every(d => d.qcIndex === null || d.qcIndex >= 70) && repeatRate <= 25 && <div style={{ fontSize: 12, color: "#94A3B8" }}>No thresholds currently breached.</div>}
              </div>
            </div>
          </div>
        )}

        {/* DISTRICTS & YARDS */}
        {tab === "districts" && (
          <div>
            <div style={{ display: "flex", gap: 8, marginBottom: 18, flexWrap: "wrap" }}>
              <button onClick={() => setSelDistrict(null)} style={{ background: selDistrict === null ? "#3B82F6" : "rgba(255,255,255,0.04)", border: `1px solid ${selDistrict === null ? "#3B82F6" : "rgba(255,255,255,0.1)"}`, color: "#F1F5F9", padding: "6px 14px", borderRadius: 8, cursor: "pointer", fontSize: 12 }}>All</button>
              {DISTRICTS.map(d => (
                <button key={d.id} onClick={() => setSelDistrict(d.id === selDistrict ? null : d.id)} style={{ background: selDistrict === d.id ? `${d.color}20` : "rgba(255,255,255,0.03)", border: `1px solid ${selDistrict === d.id ? d.color : "rgba(255,255,255,0.08)"}`, color: selDistrict === d.id ? d.color : "#94A3B8", padding: "6px 14px", borderRadius: 8, cursor: "pointer", fontSize: 12 }}>{d.abbr}</button>
              ))}
            </div>

            {districtStats.filter(d => !selDistrict || d.id === selDistrict).map(d => (
              <div key={d.id} style={{ background: "rgba(255,255,255,0.02)", border: `1px solid ${d.color}30`, borderRadius: 14, overflow: "hidden", marginBottom: 14 }}>
                <div style={{ padding: "16px 22px", background: `${d.color}0A`, borderBottom: `1px solid ${d.color}20`, display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 10 }}>
                  <div>
                    <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 6 }}>
                      <span style={{ fontSize: 10, fontWeight: 700, color: d.color, background: `${d.color}20`, padding: "2px 8px", borderRadius: 4, fontFamily: "monospace" }}>{d.id}</span>
                      <span style={{ fontSize: 15, fontWeight: 700 }}>{d.label}</span>
                    </div>
                    <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>{d.lines.map(l => <Tag key={l} label={l} color="#64748B" />)}</div>
                  </div>
                  <div style={{ textAlign: "right" }}>
                    <div style={{ fontSize: 36, fontWeight: 800, color: d.qcIndex === null ? "#475569" : ScoreColor(d.qcIndex), lineHeight: 1 }}>{d.qcIndex === null ? "—" : `${d.qcIndex}%`}</div>
                    <div style={{ fontSize: 9, color: "#475569", fontFamily: "monospace" }}>QC Index (weighted)</div>
                  </div>
                </div>
                <div className="qcd-grid3b" style={{ padding: "18px 22px" }}>
                  <div>
                    <div style={{ fontSize: 9, color: "#475569", fontFamily: "monospace", marginBottom: 10, letterSpacing: "0.1em" }}>SCORES</div>
                    <div style={{ fontSize: 12, color: "#CBD5E1", marginBottom: 4 }}>Interior: <b style={{ color: d.score === null ? "#475569" : ScoreColor(d.score) }}>{d.score === null ? "—" : `${d.score}%`}</b></div>
                    <div style={{ fontSize: 12, color: "#CBD5E1" }}>Glass/Window: <b style={{ color: d.glassScore === null ? "#475569" : ScoreColor(d.glassScore) }}>{d.glassScore === null ? "—" : `${d.glassScore}%`}</b></div>
                  </div>
                  <div>
                    <div style={{ fontSize: 9, color: "#475569", fontFamily: "monospace", marginBottom: 10, letterSpacing: "0.1em" }}>INSPECTIONS LOGGED</div>
                    <div style={{ fontSize: 26, fontWeight: 800 }}>{d.inspCount}</div>
                    <div style={{ fontSize: 10, color: "#475569", fontFamily: "monospace" }}>Yards: {d.yards.join(", ")}</div>
                  </div>
                  <div>
                    <div style={{ fontSize: 9, color: "#475569", fontFamily: "monospace", marginBottom: 10, letterSpacing: "0.1em" }}>CORRECTIVE ACTIONS</div>
                    <div style={{ fontSize: 26, fontWeight: 800, color: d.dOpen >= 4 ? "#EF4444" : "#F59E0B" }}>{d.dOpen}<span style={{ fontSize: 13, color: "#475569" }}> open</span></div>
                    {d.dOverdue > 0 && <div style={{ marginTop: 6 }}><Tag label={`${d.dOverdue} overdue`} color="#EF4444" /></div>}
                  </div>
                </div>
              </div>
            ))}

            <div style={{ marginTop: 16, padding: "16px 20px", background: "rgba(59,130,246,0.07)", border: "1px solid rgba(59,130,246,0.18)", borderRadius: 12 }}>
              <div style={{ fontSize: 10, fontWeight: 700, color: "#3B82F6", fontFamily: "monospace", marginBottom: 10 }}>SHARED YARDS — COORDINATE INSPECTION TIMING</div>
              <div className="qcd-grid3b">
                {[
                  { yard: "KYD (Kensington)", dists: ["RI", "MED", "SWS"], note: "Highest-traffic shared yard — schedule separate inspections per district" },
                  { yard: "Blue Island Yard", dists: ["RI", "MED", "SWS"], note: "Coordinate with Rock Island and MED supervisors before each visit" },
                  { yard: "OTC (Ogilvie Transportation Center)", dists: ["UP"], note: "UP downtown terminal — UP-N, UP-NW, UP-W trains arrive here. Focus district location." },
                  { yard: "California Ave (M19A)", dists: ["UP"], note: "UP coach yard — UP-N, UP-NW, UP-W all stage here" },
                ].map(y => (
                  <div key={y.yard} style={{ padding: "12px 14px", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: 10 }}>
                    <div style={{ fontSize: 12, fontWeight: 600, color: "#CBD5E1", marginBottom: 6 }}>{y.yard}</div>
                    <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 6 }}>{y.dists.map(id => <Tag key={id} label={id} color={DIST_MAP[id].color} />)}</div>
                    <div style={{ fontSize: 11, color: "#475569", fontStyle: "italic" }}>{y.note}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* TRENDS */}
        {tab === "trends" && (
          <div>
            <div style={{ display: "flex", gap: 10, marginBottom: 18, alignItems: "center" }}>
              <select value={trendDist} onChange={e => setTrendDist(e.target.value)} style={inputStyle}>
                <option value="All">All Districts</option>
                {DISTRICTS.map(d => <option key={d.id} value={d.id}>{d.label}</option>)}
              </select>
              <span style={{ fontSize: 10, color: "#475569", fontFamily: "monospace" }}>Weekly average score, {trendDist === "All" ? "system-wide" : trendDist}</span>
            </div>
            {(() => {
              const rows = inspections.filter(r => trendDist === "All" || r.district === trendDist);
              const wk = {};
              rows.forEach(r => { if (!wk[r.weekEnding]) wk[r.weekEnding] = []; wk[r.weekEnding].push(r.interior); });
              const series = Object.keys(wk).sort().map(k => ({ week: k.slice(5), avgScore: avgOf(wk[k]), n: wk[k].length }));
              const latest = series[series.length - 1], prev = series[series.length - 2];
              const delta = latest && prev ? latest.avgScore - prev.avgScore : null;
              return (
                <>
                  <div style={{ display: "flex", gap: 12, marginBottom: 18, flexWrap: "wrap" }}>
                    <KPICard label="Latest Week Score" value={latest ? `${latest.avgScore}%` : "—"} sub={latest ? `Week ending ${latest.week}` : ""} color="#3B82F6"
                      trend={delta !== null ? { up: delta >= 0, label: `${delta >= 0 ? "+" : ""}${delta} pts vs prior week` } : null} />
                  </div>
                  <Card>
                    <SecTitle>Week-over-Week Average Score</SecTitle>
                    {series.length > 1 ? (
                      <ResponsiveContainer width="100%" height={280}>
                        <LineChart data={series}>
                          <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                          <XAxis dataKey="week" tick={{ fill: "#64748B", fontSize: 10, fontFamily: "monospace" }} axisLine={false} tickLine={false} />
                          <YAxis domain={[0, 100]} tick={{ fill: "#64748B", fontSize: 11 }} axisLine={false} tickLine={false} />
                          <Tooltip contentStyle={{ background: "#1E293B", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 8, color: "#F1F5F9", fontSize: 11 }} />
                          <Line type="monotone" dataKey="avgScore" stroke="#3B82F6" strokeWidth={2.5} dot={{ r: 3, fill: "#3B82F6" }} name="Avg Score" />
                        </LineChart>
                      </ResponsiveContainer>
                    ) : <div style={{ padding: 28, textAlign: "center", color: "#475569", fontFamily: "monospace", fontSize: 12 }}>Not enough weeks logged yet.</div>}
                  </Card>
                </>
              );
            })()}

            <Card style={{ marginTop: 18 }}>
              <SecTitle color="#10B981">District QC Index — Current Period</SecTitle>
              <ResponsiveContainer width="100%" height={250}>
                <BarChart data={districtStats.filter(d => d.qcIndex !== null).map(d => ({ name: d.abbr, score: d.qcIndex }))} barSize={38}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" vertical={false} />
                  <XAxis dataKey="name" tick={{ fill: "#94A3B8", fontSize: 12, fontFamily: "monospace" }} axisLine={false} tickLine={false} />
                  <YAxis domain={[0, 100]} tick={{ fill: "#64748B", fontSize: 11 }} axisLine={false} tickLine={false} />
                  <Tooltip contentStyle={{ background: "#1E293B", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 8, color: "#F1F5F9", fontSize: 12 }} formatter={v => [`${v}%`, "QC Index"]} />
                  <Bar dataKey="score" radius={[6, 6, 0, 0]}>
                    {districtStats.filter(d => d.qcIndex !== null).map((d, i) => <Cell key={i} fill={ScoreColor(d.qcIndex)} />)}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </Card>

            <div style={{ marginTop: 18, padding: "14px 18px", background: "rgba(59,130,246,0.07)", border: "1px solid rgba(59,130,246,0.18)", borderRadius: 10, fontSize: 11, color: "#93C5FD", fontFamily: "monospace" }}>
              ▸ QC Index weighting: Interior 60% · Complaints 20% · Corrective Action Closure 12% · Inspection Completion 8%. Treat week-to-week moves on fewer than ~15 inspections as noise, not signal — a rolling 4-week average is a better read once real logging is underway.
            </div>
          </div>
        )}

        {/* DEFECTS & ROOT CAUSE */}
        {tab === "defects" && (
          <div>
            <div style={{ display: "flex", gap: 12, marginBottom: 22, flexWrap: "wrap" }}>
              <KPICard label="Defect Records" value={defectRecords.length} sub={`of ${totalInsp} inspections`} color="#F59E0B" />
              <KPICard label="Critical Defects" value={criticalCount} sub={`${criticalRate}% of inspections`} color="#EF4444" />
              <KPICard label="Repeat-Defect Rate" value={`${repeatRate}%`} sub="Same car + category within 30 days" color="#8B5CF6" />
              <KPICard label="Top Category" value={paretoData[0]?.name || "—"} sub={paretoData[0] ? `${paretoData[0].value} occurrences` : ""} color="#3B82F6" />
            </div>

            <Card style={{ marginBottom: 18 }}>
              <SecTitle color="#F59E0B">Pareto — Defect Category Frequency</SecTitle>
              <p style={{ margin: "-10px 0 14px", fontSize: 10, color: "#475569", fontFamily: "monospace" }}>Bars = count of that defect category; line = cumulative % of all defects. The categories left of where the line crosses ~80% are the few causes producing most of your failures.</p>
              {paretoData.length > 0 ? (
                <ResponsiveContainer width="100%" height={280}>
                  <ComposedChart data={paretoData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                    <XAxis dataKey="name" tick={{ fill: "#94A3B8", fontSize: 9, fontFamily: "monospace" }} axisLine={false} tickLine={false} angle={-20} textAnchor="end" height={70} />
                    <YAxis yAxisId="l" tick={{ fill: "#64748B", fontSize: 10 }} axisLine={false} tickLine={false} />
                    <YAxis yAxisId="r" orientation="right" domain={[0, 100]} tick={{ fill: "#64748B", fontSize: 10 }} axisLine={false} tickLine={false} />
                    <Tooltip contentStyle={{ background: "#1E293B", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 8, color: "#F1F5F9", fontSize: 11 }} />
                    <Bar yAxisId="l" dataKey="value" fill="#F59E0B" name="Count" radius={[4, 4, 0, 0]} />
                    <Line yAxisId="r" type="monotone" dataKey="cumPct" stroke="#3B82F6" strokeWidth={2.5} dot={{ r: 3, fill: "#3B82F6" }} name="Cumulative %" />
                  </ComposedChart>
                </ResponsiveContainer>
              ) : <div style={{ padding: 28, textAlign: "center", color: "#475569", fontFamily: "monospace", fontSize: 12 }}>No defects logged yet.</div>}
            </Card>

            <div className="qcd-grid2" style={{ marginBottom: 18 }}>
              <Card>
                <SecTitle color="#8B5CF6">Root Cause Breakdown</SecTitle>
                <ResponsiveContainer width="100%" height={240}>
                  <BarChart data={rootCauseData} layout="vertical" margin={{ left: 10 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" horizontal={false} />
                    <XAxis type="number" tick={{ fill: "#64748B", fontSize: 10 }} axisLine={false} tickLine={false} />
                    <YAxis type="category" dataKey="name" width={150} tick={{ fill: "#94A3B8", fontSize: 9, fontFamily: "monospace" }} axisLine={false} tickLine={false} />
                    <Tooltip contentStyle={{ background: "#1E293B", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 8, color: "#F1F5F9", fontSize: 11 }} />
                    <Bar dataKey="value" fill="#8B5CF6" radius={[0, 4, 4, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </Card>
              <Card>
                <SecTitle color="#EF4444">Heat Map — Avg Score by District & Shift</SecTitle>
                <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                  <div style={{ display: "grid", gridTemplateColumns: "70px 1fr 1fr", gap: 8 }}>
                    <div />
                    {SHIFTS.map(s => <div key={s} style={{ fontSize: 9, color: "#64748B", fontFamily: "monospace", textAlign: "center" }}>{s} SHIFT</div>)}
                  </div>
                  {heatData.map(h => (
                    <div key={h.district.id} style={{ display: "grid", gridTemplateColumns: "70px 1fr 1fr", gap: 8, alignItems: "center" }}>
                      <Tag label={h.district.abbr} color={h.district.color} />
                      {h.cells.map(c => (
                        <div key={c.shift} style={{ background: c.avgScore === null ? "rgba(255,255,255,0.03)" : `${ScoreColor(c.avgScore)}22`, border: `1px solid ${c.avgScore === null ? "rgba(255,255,255,0.06)" : ScoreColor(c.avgScore)}50`, borderRadius: 8, padding: "10px 6px", textAlign: "center" }}>
                          <div style={{ fontSize: 16, fontWeight: 800, color: c.avgScore === null ? "#475569" : ScoreColor(c.avgScore) }}>{c.avgScore !== null ? `${c.avgScore}%` : "—"}</div>
                          <div style={{ fontSize: 8, color: "#64748B", fontFamily: "monospace" }}>{c.n} insp · {c.failRate !== null ? `${c.failRate}% fail` : ""}</div>
                        </div>
                      ))}
                    </div>
                  ))}
                </div>
              </Card>
            </div>

            <div style={{ padding: "14px 18px", background: "rgba(139,92,246,0.07)", border: "1px solid rgba(139,92,246,0.2)", borderRadius: 10, fontSize: 11, color: "#C4B5FD", fontFamily: "monospace" }}>
              ▸ A district and shift showing both a low average score and a high fail rate is where a staffing or scheduling change would show up fastest — confirm with the root-cause column before reassigning anyone. Correlation between shift and score here is not proof of cause.
            </div>
          </div>
        )}

        {/* CORRECTIVE ACTIONS */}
        {tab === "actions" && (
          <div>
            <div style={{ display: "flex", gap: 12, marginBottom: 22, flexWrap: "wrap" }}>
              <KPICard label="Open Actions" value={openActions.length} color="#F59E0B" />
              <KPICard label="Overdue" value={overdueActions.length} color={overdueActions.length ? "#EF4444" : "#10B981"} />
              <KPICard label="Closure Rate" value={`${caClosureRate}%`} sub={`${closedActions.length}/${actions.length} closed`} color="#3B82F6" />
              <KPICard label="Closed On Time" value={`${onTimeRate}%`} sub="Of closed actions" color="#10B981" />
              <KPICard label="Avg Days to Close" value={avgDaysToClose} color="#8B5CF6" />
              <KPICard label="Effectiveness Verified" value={`${effectivenessRate}%`} sub="Reinspection confirmed fix held" color="#10B981" />
            </div>

            <div style={{ display: "flex", gap: 10, marginBottom: 18, flexWrap: "wrap", alignItems: "center" }}>
              {[
                { label: "District", val: fDist, set: setFDist, opts: ["All", ...DISTRICTS.map(d => d.id)] },
                { label: "Status", val: fStatus, set: setFStatus, opts: ["All", "Open", "In Progress", "Closed"] },
                { label: "Severity", val: fSev, set: setFSev, opts: ["All", "HIGH", "MED", "LOW"] },
              ].map(f => (
                <select key={f.label} value={f.val} onChange={e => f.set(e.target.value)} style={inputStyle}>
                  {f.opts.map(o => <option key={o}>{o}</option>)}
                </select>
              ))}
              <label style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 12, color: "#CBD5E1" }}>
                <input type="checkbox" checked={fOverdueOnly} onChange={e => setFOverdueOnly(e.target.checked)} /> Overdue only
              </label>
              {isLive ? <span style={{ marginLeft: "auto", fontSize: 10, color: "#475569", fontFamily: "monospace" }}>Actions open automatically from any area scored 1 or 2</span> : <button onClick={() => setShowActionForm(!showActionForm)} style={{ marginLeft: "auto", background: "#3B82F6", border: "none", color: "#fff", padding: "8px 16px", borderRadius: 8, cursor: "pointer", fontSize: 12, fontWeight: 600 }}>+ Log Action</button>}
            </div>

            {showActionForm && (
              <div style={{ background: "rgba(59,130,246,0.07)", border: "1px solid rgba(59,130,246,0.2)", borderRadius: 12, padding: 16, marginBottom: 18, display: "flex", gap: 10, flexWrap: "wrap", alignItems: "flex-end" }}>
                <Field label="DISTRICT"><select value={na.district} onChange={e => setNa({ ...na, district: e.target.value, yard: DIST_YARDS[e.target.value][0], line: DIST_LINES[e.target.value][0], owner: CA_OWNERS[e.target.value] })} style={inputStyle}>{DISTRICTS.map(d => <option key={d.id} value={d.id}>{d.id}</option>)}</select></Field>
                <Field label="YARD"><select value={na.yard} onChange={e => setNa({ ...na, yard: e.target.value })} style={inputStyle}>{(DIST_YARDS[na.district] || []).map(y => <option key={y} value={y}>{y}</option>)}</select></Field>
                <Field label="LINE"><select value={na.line} onChange={e => setNa({ ...na, line: e.target.value })} style={inputStyle}>{(DIST_LINES[na.district] || []).map(l => <option key={l} value={l}>{l}</option>)}</select></Field>
                <Field label="CAR #"><input type="text" value={na.car} placeholder="e.g. 7714" onChange={e => setNa({ ...na, car: e.target.value })} style={inputStyle} /></Field>
                <Field label="ISSUE"><input type="text" value={na.issue} placeholder="Describe the issue..." onChange={e => setNa({ ...na, issue: e.target.value })} style={{ ...inputStyle, minWidth: 200 }} /></Field>
                <Field label="CATEGORY"><select value={na.category} onChange={e => setNa({ ...na, category: e.target.value })} style={inputStyle}>{DEFECT_CATEGORIES.map(c => <option key={c}>{c}</option>)}</select></Field>
                <Field label="ROOT CAUSE"><select value={na.rootCause} onChange={e => setNa({ ...na, rootCause: e.target.value })} style={inputStyle}>{ROOT_CAUSES.map(c => <option key={c}>{c}</option>)}</select></Field>
                <Field label="SEVERITY"><select value={na.severity} onChange={e => setNa({ ...na, severity: e.target.value })} style={inputStyle}>{["HIGH", "MED", "LOW"].map(s => <option key={s}>{s}</option>)}</select></Field>
                <Field label="OWNER"><input type="text" value={na.owner} onChange={e => setNa({ ...na, owner: e.target.value })} style={inputStyle} /></Field>
                <Field label="DUE DATE"><input type="date" value={na.due} onChange={e => setNa({ ...na, due: e.target.value })} style={inputStyle} /></Field>
                <button onClick={addAction} style={{ background: "#10B981", border: "none", color: "#fff", padding: "8px 16px", borderRadius: 8, cursor: "pointer", fontSize: 12, fontWeight: 600 }}>Add</button>
              </div>
            )}

            <div style={{ background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: 14, overflow: "hidden" }}>
              <div style={{ overflowX: "auto", WebkitOverflowScrolling: "touch" }}>
                <div style={{ minWidth: 1080 }}>
                  <div style={{ display: "grid", gridTemplateColumns: "0.5fr 0.9fr 1.6fr 0.9fr 0.55fr 0.9fr 0.65fr 0.65fr 0.7fr 0.8fr", padding: "10px 16px", background: "rgba(255,255,255,0.04)", borderBottom: "1px solid rgba(255,255,255,0.06)" }}>
                    {["Dist", "Yard", "Issue", "Root Cause", "Sev", "Owner", "Opened", "Due", "Days Open", "Status"].map(h => (
                      <div key={h} style={{ fontSize: 8, color: "#475569", fontFamily: "monospace", letterSpacing: "0.1em", textTransform: "uppercase" }}>{h}</div>
                    ))}
                  </div>
                  {filteredActions.map((a, i) => {
                    const dist = DIST_MAP[a.district];
                    const overdue = a.status !== "Closed" && !!a.due && new Date(a.due) < today;
                    const daysOpen = daysBetween(new Date(a.dateOpened), a.dateClosed ? new Date(a.dateClosed) : today);
                    return (
                      <div key={a.id} style={{ display: "grid", gridTemplateColumns: "0.5fr 0.9fr 1.6fr 0.9fr 0.55fr 0.9fr 0.65fr 0.65fr 0.7fr 0.8fr", padding: "11px 16px", borderBottom: "1px solid rgba(255,255,255,0.04)", background: overdue ? "rgba(239,68,68,0.06)" : i % 2 === 0 ? "transparent" : "rgba(255,255,255,0.01)", alignItems: "center" }}>
                        <div><Tag label={a.district} color={dist ? dist.color : "#64748B"} /></div>
                        <div style={{ fontSize: 11, color: "#94A3B8" }}>{a.yard}</div>
                        <div style={{ fontSize: 12, color: "#CBD5E1" }}>{a.issue}{a.car ? ` (Car ${a.car})` : ""}</div>
                        <div style={{ fontSize: 10, color: "#64748B", fontFamily: "monospace" }}>{a.rootCause}</div>
                        <div><span style={{ fontSize: 8, fontWeight: 700, color: SEV_CLR[a.severity], background: `${SEV_CLR[a.severity]}18`, padding: "2px 6px", borderRadius: 3, fontFamily: "monospace" }}>{a.severity}</span></div>
                        <div style={{ fontSize: 11, color: "#CBD5E1" }}>{a.owner}</div>
                        <div style={{ fontSize: 9, color: "#475569", fontFamily: "monospace" }}>{a.dateOpened}</div>
                        <div style={{ fontSize: 9, color: overdue ? "#EF4444" : "#475569", fontFamily: "monospace", fontWeight: overdue ? 700 : 400 }}>{a.due || "No due date"}{overdue ? " ⚠" : ""}</div>
                        <div style={{ fontSize: 11, color: "#94A3B8", fontFamily: "monospace" }}>{daysOpen}d</div>
                        <div onClick={() => toggleStatus(a.id)} style={{ cursor: "pointer" }}>
                          <span style={{ fontSize: 8, fontWeight: 700, color: STS_CLR[a.status], background: `${STS_CLR[a.status]}18`, padding: "2px 7px", borderRadius: 3, fontFamily: "monospace" }}>{a.status}</span>
                          {a.status === "Closed" && a.reinspectionResult !== "Pending" && <div style={{ fontSize: 8, color: a.reinspectionResult === "Pass" ? "#10B981" : "#EF4444", fontFamily: "monospace", marginTop: 2 }}>Reinsp: {a.reinspectionResult}</div>}
                        </div>
                      </div>
                    );
                  })}
                  {filteredActions.length === 0 && <div style={{ padding: 28, textAlign: "center", color: "#475569", fontFamily: "monospace", fontSize: 12 }}>No actions match filters.</div>}
                </div>
              </div>
            </div>
            <div style={{ marginTop: 7, fontSize: 10, color: "#475569", fontFamily: "monospace" }}>Click status badge to cycle: Open → In Progress → Closed. Rows highlighted red are past their due date as of today.</div>
          </div>
        )}

        {/* STAFFING & PRODUCTIVITY */}
        {tab === "staffing" && (
          <div>
            <div style={{ display: "flex", gap: 12, marginBottom: 22, flexWrap: "wrap" }}>
              <KPICard label="Avg Scheduled Time" value={fmtMin(avgOf(inspections.map(r => r.scheduledMin)))} sub="Per car, all districts" color="#3B82F6" />
              <KPICard label="Avg Actual Time" value={fmtMin(avgOf(inspections.map(r => r.actualMin)))} sub="Per car, all districts" color="#F59E0B" />
              <KPICard label="Avg Crew Size" value={avgOf(inspections.map(r => r.employees)) ?? "—"} sub={isLive ? "Not captured on the inspection form yet" : "Employees assigned per inspection"} color="#8B5CF6" />
            </div>

            <Card style={{ marginBottom: 18 }}>
              <SecTitle color="#F59E0B">Planned vs. Actual Cleaning Time by Yard</SecTitle>
              <p style={{ margin: "-10px 0 14px", fontSize: 10, color: "#475569", fontFamily: "monospace" }}>Yards where actual time runs short of scheduled are where the layover window may not be long enough to clean to standard — worth checking before holding those crews to the same bar as yards with more time.</p>
              <div style={{ overflowX: "auto" }}>
                <div style={{ minWidth: 620 }}>
                  <div style={{ display: "grid", gridTemplateColumns: "1.6fr 0.6fr 1fr 1fr 1fr 0.8fr", padding: "10px 16px", background: "rgba(255,255,255,0.04)", borderBottom: "1px solid rgba(255,255,255,0.06)" }}>
                    {["Yard", "Dist", "Scheduled", "Actual", "Delta", "Avg Score"].map(h => (
                      <div key={h} style={{ fontSize: 8, color: "#475569", fontFamily: "monospace", letterSpacing: "0.1em", textTransform: "uppercase" }}>{h}</div>
                    ))}
                  </div>
                  {yardRows.map((y, i) => {
                    const dist = DIST_MAP[y.district];
                    const short = y.delta !== null && y.delta < 0;
                    return (
                      <div key={y.yard + y.district} style={{ display: "grid", gridTemplateColumns: "1.6fr 0.6fr 1fr 1fr 1fr 0.8fr", padding: "11px 16px", borderBottom: "1px solid rgba(255,255,255,0.04)", background: i % 2 === 0 ? "transparent" : "rgba(255,255,255,0.01)", alignItems: "center" }}>
                        <div style={{ fontSize: 12, color: "#CBD5E1" }}>{y.yard}</div>
                        <div><Tag label={dist.abbr} color={dist.color} /></div>
                        <div style={{ fontSize: 12, color: "#94A3B8", fontFamily: "monospace" }}>{fmtMin(y.scheduledMin)}</div>
                        <div style={{ fontSize: 12, color: "#94A3B8", fontFamily: "monospace" }}>{fmtMin(y.actualMin)}</div>
                        {y.delta === null
                          ? <div style={{ fontSize: 12, color: "#475569", fontFamily: "monospace" }}>—</div>
                          : <div style={{ fontSize: 12, fontWeight: 700, color: short ? "#EF4444" : "#10B981", fontFamily: "monospace" }}>{short ? "" : "+"}{y.delta} min {short && <Tag label="TIGHT" color="#EF4444" />}</div>}
                        <div style={{ fontSize: 12, fontWeight: 700, color: ScoreColor(y.avgScore) }}>{y.avgScore}%</div>
                      </div>
                    );
                  })}
                </div>
              </div>
            </Card>

            <div style={{ padding: "14px 18px", background: "rgba(139,92,246,0.07)", border: "1px solid rgba(139,92,246,0.2)", borderRadius: 10, fontSize: 11, color: "#C4B5FD", fontFamily: "monospace" }}>
              ▸ A yard combining a negative time delta with a low avg score is a workload/time problem, not necessarily a coaching problem — raise it as a scheduling constraint before treating it as a performance issue.
            </div>
          </div>
        )}

        {/* COMPLAINTS */}
        {tab === "complaints" && (
          <div>
            <div style={{ display: "flex", gap: 12, marginBottom: 22, flexWrap: "wrap" }}>
              {districtStats.map(d => (
                <KPICard key={d.id} label={d.abbr} value={d.complaints} sub={d.label} color={d.complaints >= 8 ? "#EF4444" : d.complaints >= 5 ? "#F59E0B" : "#10B981"} />
              ))}
            </div>
            <Card style={{ marginBottom: 18 }}>
              <SecTitle>Complaint-Linked Inspections by Month</SecTitle>
              <ResponsiveContainer width="100%" height={260}>
                <LineChart data={monthlyTrend}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                  <XAxis dataKey="month" tick={{ fill: "#64748B", fontSize: 11, fontFamily: "monospace" }} axisLine={false} tickLine={false} />
                  <YAxis tick={{ fill: "#64748B", fontSize: 11 }} axisLine={false} tickLine={false} />
                  <Tooltip contentStyle={{ background: "#1E293B", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 8, color: "#F1F5F9", fontSize: 11 }} />
                  <Line type="monotone" dataKey="complaints" stroke="#EF4444" strokeWidth={2.5} dot={{ r: 3, fill: "#EF4444" }} name="Complaints" />
                </LineChart>
              </ResponsiveContainer>
            </Card>
            {(() => {
              const worst = [...districtStats].sort((a, b) => b.complaints - a.complaints).slice(0, 2);
              return (
                <div style={{ padding: "14px 18px", background: "rgba(239,68,68,0.07)", border: "1px solid rgba(239,68,68,0.2)", borderRadius: 10, fontSize: 11, color: "#FCA5A5", fontFamily: "monospace" }}>
                  ▸ {worst.map(w => w.abbr).join(" and ")} are your highest complaint-linked districts this window.{isLive ? " Complaint-linked here means a Complaint-Driven inspection or one tied to a Jira ticket; Jira stays the system of record for complaint volume." : " Both share KYD (Kensington) and Blue Island Yard — prioritize inspection frequency at those two locations."}
                </div>
              );
            })()}
          </div>
        )}

      </div>
    </div>
  );
}

ReactDOM.createRoot(document.getElementById("root")).render(<MetraDashboard />);
